# Port used for TCP connection
tcp-port: 30813

# Port used for UDP connection
udp-port: 30814

# Default: 4 - Max players allowed to connect to the server
max-players: 4

# Default: true - Set this to false if you don't use mods
enable-mods: true

# Default: 15 - The delay before a player get kicked from the server because he don't answer.
players-timeout-delay: 15